### ISSUE TITLE
Import as a module

### ISSUE THREAD

**Issue by absowoot** [sezaru/flashy#3]
The project I'm working on has some large dependencies, so I've enabled splitting in esbuild and set `type="module"` for app.js

When trying to import Flashy I am receiving the following error: 

```
[FlashHook is undefined](flashy.min.js:22 Uncaught ReferenceError: FlashHook is not defined)
```

To replicate, just change app.js type to module. After looking through the JS, it seems that [line 5 here is missing a const](https://github.com/sezaru/flashy/blob/b40ae5c90f85ff5cd856b110bfacc8b9c6ed65e8/assets/js/hooks/flash_hook.js#L5C1-L5C1).

After adding the const, I am able to see the flash notifications but I am also seeing `unknown hook found for "FlashHook"` in the console. Any thoughts on how to fix this?

**Comment by sezaru** [comment]
Fixed in version 0.2.5 :)
