### ISSUE TITLE
Unknown hook found

### ISSUE THREAD

**Issue by teatimes** [sezaru/flashy#4]
I followed the instructions, but when running, I get errors in the console for unknown hook found for both `FlashHook` and `DisconnectedNotificationHook`. I temporarily fixed it by creating the hooks in my own code and importing them, but I assume I should not have to?

I'm using Elixir 1.15.3, Phoenix 1.7.10 and Phoenix Liveview 0.20.1

**Comment by Gomozov** [comment]
Hi teatimes!
What does the part of your code look like where hooks are defined?

**Comment by Gomozov** [comment]
You can try this:

import FlashyHooks from "flashy"

let Hooks = FlashyHooks

**Comment by sezaru** [comment]
The problem is that `FlashyHooks` is a object of hooks, not just one hook.

This means that you need to "merge" your hooks object with the `FlashyHooks`.

For example, you can write it like this:

```javascript
let Hooks = {...FlashyHooks}
```

Or the way @Gomozov suggested.
